### ISSUE TITLE
Incompatible import of BatchEncoding from transformers.data.data_collator in transformers==4.26.1

### ISSUE THREAD

**Issue by handecelikkanat** [Kaleidophon/nlp-uncertainty-zoo#8]
Import command:
`from nlp_uncertainty_zoo import VariationalBert`

results in the error:
```
  File "<path-to-python3.8>/site-packages/nlp_uncertainty_zoo/utils/data.py", line 22, in <module>
    from transformers.data.data_collator import BatchEncoding, _collate_batch
ImportError: cannot import name 'BatchEncoding' from 'transformers.data.data_collator' (<path-to-python3.8>/site-packages/transformers/data/data_collator.py)
```

under library installation:
```
$ pip show transformers
Name: transformers
Version: 4.26.1
```

(This version of transformers seems to have a `BatchEncoding `defined in: `transformers/tokenization_utils_base.py`)

**Comment by Kaleidophon** [comment]
Hey! Thanks for reporting your bugs :-) I will take a look asap

**Comment by Kaleidophon** [comment]
I updated the main branch with hot fixes and updated the pip version to 0.9.1, let me know and reopen any of the issues if you encounter any more problems! Thanks a lot :-)

**Comment by handecelikkanat** [comment]
Thank you for the prompt reply! Im still having issues with this part, as follows:

**Option 1. installation via pip install gives same error on import:**
`Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nlp_uncertainty_zoo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path-to-python3.8/site-packages/nlp_uncertainty_zoo/__init__.py", line 28, in <module>
    from nlp_uncertainty_zoo.utils.data import (
  File "/path-to-python3.8/site-packages/nlp_uncertainty_zoo/utils/data.py", line 22, in <module>
    from transformers.data.data_collator import BatchEncoding, _collate_batch
ImportError: cannot import name 'BatchEncoding' from 'transformers.data.data_collator' (/path-to-python3.8/site-packages/transformers/data/data_collator.py)`

**Option 2: installation via setup.py has library conflicts within itself, requiring urllib3<1.26 and urllib3>=1.26:**
`Processing dependencies for nlp-uncertainty-zoo==1.0.1
Searching for urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
Reading https://pypi.org/simple/urllib3/
Downloading https://files.pythonhosted.org/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl#sha256=f5321fbe4bf3fefa0efd0bfe7fb14e90909eb62a48ccda331726b4319897dd5e
Best match: urllib3 1.25.11
Processing urllib3-1.25.11-py2.py3-none-any.whl
Installing urllib3-1.25.11-py2.py3-none-any.whl to /path-to-python3.8/site-packages
Adding urllib3 1.25.11 to easy-install.pth file

Installed /path-to-python3.8/site-packages/urllib3-1.25.11-py3.8.egg
error: urllib3 1.25.11 is installed but urllib3>=1.26.11; python_version >= "3.6" is required by {'sentry-sdk'}`

**Comment by Kaleidophon** [comment]
I am sorry, this is frustrating! I will look back into this and see if I can set up some automated testing for the installation. Thanks for the reporting!

**Comment by Kaleidophon** [comment]
Have you created a fresh install of version 1.0.1? Because trying that it seems on my side that I can install it and import the package without any problems.

**Comment by handecelikkanat** [comment]
Oh yes, my mistake! Apologies and thank you!
